apiVersion: v1
kind: Secret
metadata:
  name: kubenexus-alert-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  discord-webhook-url: {{ .Values.alerts.discordWebhookUrl | default "" | quote }}
  mail-username: {{ .Values.alerts.mailUsername | default "" | quote }}
  mail-password: {{ .Values.alerts.mailPassword | default "" | quote }}
