apiVersion: v1
kind: Service
metadata:
  name: kubenexus-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kubenexus-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP