apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenexus-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kubenexus-backend
  template:
    metadata:
      labels:
        app: kubenexus-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: kubenexus-sa
      containers:
      - name: kubenexus-backend
        image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        workingDir: /app
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: kubenexus-alert-secret
              key: discord-webhook-url
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kubenexus-alert-secret
              key: mail-username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubenexus-alert-secret
              key: mail-password
        ports:
        - containerPort: {{ .Values.backend.port }}
        volumeMounts:
        - name: backend-code
          mountPath: /app/main.py
          subPath: main.py
        envFrom:
        - configMapRef:
            name: kubenexus-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 12
      volumes:
      - name: backend-code
        configMap:
          name: kubenexus-backend-code
