apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenexus-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: kubenexus-frontend
  template:
    metadata:
      labels:
        app: kubenexus-frontend
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: kubenexus-frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: kubenexus-frontend-config