namespace: kubenexus

backend:
  image: mohammedomar02/kubenexus-backend
  tag: latest
  replicas: 1
  port: 8000

frontend:
  image: mohammedomar02/kubenexus-frontend
  tag: latest
  replicas: 1
  port: 80
  nodePort: 30080

ollama:
  host: http://host.minikube.internal:11434
  model: gemma3:1b

alerts:
  discordWebhookUrl: "https://discord.com/api/webhooks/1487759737490640977/N3I1R63_vJ4ApE2RjWAPIoDrI0SlnUB4I5aubrCk2fkthC5r8IlFwVrBQgRc7FjzFmZr"
  mailUsername: ""
  mailPassword: ""