name: KubeNexus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Lint Helm Chart
        run: helm lint helm/kubenexus

  build-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build -t kubenexus-backend:ci-test ./backend
          
      - name: Run Trivy vulnerability scanner on Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kubenexus-backend:ci-test'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Build Frontend Image
        run: |
          docker build -t kubenexus-frontend:ci-test ./frontend

      - name: Run Trivy vulnerability scanner on Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kubenexus-frontend:ci-test'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # Automatically push to Docker Hub
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images
        if: github.event_name == 'push'
        run: |
          docker tag kubenexus-backend:ci-test ${{ secrets.DOCKER_USERNAME }}/kubenexus-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kubenexus-backend:latest
          docker tag kubenexus-frontend:ci-test ${{ secrets.DOCKER_USERNAME }}/kubenexus-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kubenexus-frontend:latest

      # Discord Webhook Notification
      - name: Send Discord Deployment Alert
        if: success() && github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "✅ **KubeNexus Deployment Successful!**\nTrivy scans passed and images have been pushed to Docker Hub! 🚀\nFrontend: `mohammedomar02/kubenexus-frontend:latest`\nBackend: `mohammedomar02/kubenexus-backend:latest`"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      # Email Notification
      - name: Send Email Alert
        if: success() && github.event_name == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ✅ KubeNexus Docker Deployment Successful 
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions
          body: The KubeNexus frontend and backend Docker images have successfully passed Trivy vulnerability scans and were pushed to Docker Hub!
