name: KubeNexus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Lint Helm Chart
        run: helm lint helm/kubenexus

  build-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build -t kubenexus-backend:ci-test ./backend
          
      - name: Run Trivy vulnerability scanner on Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kubenexus-backend:ci-test'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Build Frontend Image
        run: |
          docker build -t kubenexus-frontend:ci-test ./frontend

      - name: Run Trivy vulnerability scanner on Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kubenexus-frontend:ci-test'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # Uncomment the block below to automatically push to Docker Hub
      # - name: Login to Docker Hub
      #   if: github.event_name == 'push'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push images
      #   if: github.event_name == 'push'
      #   run: |
      #     docker tag kubenexus-backend:ci-test ${{ secrets.DOCKER_USERNAME }}/kubenexus-backend:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/kubenexus-backend:latest
      #     docker tag kubenexus-frontend:ci-test ${{ secrets.DOCKER_USERNAME }}/kubenexus-frontend:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/kubenexus-frontend:latest
